Add actions & flavors
aeecleclair/Titan pull request #170
Opened 2023-09-10 14:45 UTC by Petitoto

This PR unifies and finalizes #55 and #166.

It adds actions and flavors to Titan.

All features have been tested on my fork (https://github.com/Petitoto/Titan)

New features:
- 3 flavors : prod, alpha, dev, which edits icons and firebase configuration ; default when debugging using VSCode is dev
- workflow to build web and APK (using dev flavor) on each PR
- workflow to build AAB (signed, ready to upload to Google Play Console), IPA (unsigned for now) and Web (directly uploaded to our docker registry)

Not included (future PR):
- IPA code signing (nearly all is setup, only few changes will be required when keys will be available)
- .env flavor: only one .env for now
- assets flavors: `assets/images/icon.png` and `assets/images/logo.png` are not edited by flavors. However, they are edited by workflows

2023-09-10 23:10 UTC, Rotheem commented on .github/workflows/release-mobile.yml
> +          RELEASE_HOST: ${{ secrets.RELEASE_HOST }}
There is no use of declaring RELEASE_HOST

2023-09-14 09:10 UTC, Jake-Ransom requested changes

2023-09-14 09:10 UTC, Jake-Ransom commented on .github/workflows/release-web.yml
> +  extract-version:
Maybe we could group this workflow with the previous one, so that this job isn't declared and executed several times.

2023-10-12 06:36 UTC, Rotheem approved these changes

2023-10-15 12:59 UTC, merged