Support flavor on the web using flutter `dart-define`
aeecleclair/Titan pull request #331
Opened 2024-03-18 23:42 UTC by armanddidierjean

2024-03-19 08:19 UTC, maximeComeOn commented on README.md
>  flutter analyze --fix
It is `dart fix --apply`and we should apply it before the formating to ensure formatting is correct event after applying changes

2024-03-19 08:19 UTC, maximeComeOn commented on README.md
>  flutter analyze --fix
We can also run `dart fix --dry-run` to visualize the change that would be done if the run was with `--apply`

2024-03-19 08:26 UTC, maximeroucher commented on README.md
>  flutter analyze --fix
It is dart fix --applyand we should apply it before the formating to ensure formatting is correct event after applying changes

We can also run dart fix --dry-run to visualize the change that would be done if the run was with --apply

2024-03-19 13:59 UTC, julien4215 approved these changes

2024-03-19 20:41 UTC, guillaumetavernier approved these changes

2024-03-19 21:15 UTC, julien4215 requested changes
We need to keep defining two different environments for alpha and prod because we should not use the same value for `PLAUSIBLE_HOST` and `PLAUSIBLE_DOMAIN` in alpha or production.

2024-03-20 10:07 UTC, julien4215 approved these changes

2024-03-20 15:11 UTC, merged