password format verification
aeecleclair/Titan pull request #373
Opened 2024-05-23 17:09 UTC by Foukki

2024-05-26 19:02 UTC, maximeroucher requested changes
Can you move this logic  in the validator of the password (line 89). Doing so will prevent the user to go on next page until conditions are matched, and in case of error, the message is displayed inside the page

2024-05-31 17:11 UTC, maximeroucher approved these changes

2024-05-31 22:49 UTC, Rotheem requested changes

2024-05-31 22:49 UTC, Rotheem commented on lib/login/ui/components/login_field.dart
> +    RegExp(r'[!@#$%^&*(),.?":{}|<>]'):
You forgot - and _

2024-06-04 08:23 UTC, Rotheem approved these changes

2024-06-04 12:37 UTC, merged