Testing
aeecleclair/Titan pull request #64
Opened 2023-03-24 18:10 UTC by maximeroucher

2023-11-19 18:26 UTC, armanddidierjean reviewed
Could you add a line in the readme explaining how to run the test suite?

2023-11-19 18:26 UTC, armanddidierjean commented on coverage/lcov.info
I think we should ignore this file

2023-11-20 10:53 UTC, Petitoto approved these changes

2023-11-20 14:14 UTC, armanddidierjean requested changes

2023-11-20 14:14 UTC, armanddidierjean commented on test/admin/admin_test.dart
> +      expect(group.name, 'name'); // capitaliseAll
```suggestion
      expect(group.name, 'name');
```

2023-11-20 14:16 UTC, maximeroucher commented on pubspec.yaml
> +    image_path: "assets/images/icon.png"
It might have been included by error

2023-11-20 14:34 UTC, maximeroucher commented on test/admin/admin_test.dart
> +// ignore_for_file: invalid_use_of_protected_member
It was causing a linting error, it seems to have been fixed since, I'm removing it

2023-11-20 14:36 UTC, armanddidierjean approved these changes

2023-11-20 15:17 UTC, armanddidierjean approved these changes

2023-11-20 15:17 UTC, merged