Paiement
aeecleclair/Titan pull request #72
Opened 2023-05-15 21:26 UTC by maximeroucher

2024-09-19 07:52 UTC, Daihecyy commented
![image](https://github.com/user-attachments/assets/1125e9cd-2ef8-4100-a1ec-a0fbf1227ad3)

2025-05-05 13:27 UTC, armanddidierjean requested changes

2025-05-05 13:27 UTC, armanddidierjean commented on lib/main.dart
> +    // );
Please remove

2025-05-05 13:27 UTC, armanddidierjean commented on lib/paiement/ui/pages/main_page/seller_card/store_card.dart
> +    // final scanNotifier = ref.read(scanProvider.notifier);
```suggestion
```

2025-05-05 13:27 UTC, armanddidierjean commented on web/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js"></script>
Do we really need to load this for every session?

2025-05-05 13:27 UTC, armanddidierjean commented on web/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js"></script>
Do we really need to load this for every session?

2025-05-05 13:27 UTC, armanddidierjean commented on web/.well-known/apple-app-site-association
We can move this change in an other PR

2025-05-05 13:27 UTC, armanddidierjean commented on nginx.conf
We can move this change in an other PR

2025-05-07 18:23 UTC, armanddidierjean approved these changes

2025-05-07 19:38 UTC, merged