Add routing
aeecleclair/Titan pull request #89
Opened 2023-06-20 21:56 UTC by maximeroucher

Changing the provider based routing to a path base routing system. 
- It will enhance the web version by allowing specific link sharing.
- The usage of Qlevar_router allow to add deferred middleware which will later be used to deferred the loading of entire module, reducing then th size of main.js for web

2023-06-28 18:55 UTC, Rotheem requested changes

2023-06-28 18:55 UTC, Rotheem commented on lib/settings/ui/pages/main_page/main_page.dart
> +                      QR.navigator
Should be QR.to instead of QR.navigator.push

2023-06-30 17:13 UTC, Rotheem approved these changes

2023-07-01 20:55 UTC, Rotheem approved these changes

2023-07-02 09:54 UTC, armanddidierjean approved these changes
It works really well 🚀

2023-07-02 10:14 UTC, merged